test_dataset:
  dataset:
    name: image-folder
    args:
      root_path: /nobackup/gpu_d_00993_t3/mtk19837/dataset/sr_data/benchmark/Set14/HR
  wrapper:
    name: sr-implicit-downsampled-cascaded
    args:
      batch_size: 1
      scale_max: 6
      scale_base: 4
      window_size: 8
      phase: valid
  batch_size: 1
  
eval_type: benchmark-6
eval_bsize: 30000

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}