train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: /nobackup/gpu_d_00993_t3/mtk19837/dataset/sr_data/DIV2K/DIV2K_train_HR
      repeat: 40 # 20 for bz 16
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled-cascaded
    args:
      inp_size: 48
      batch_size: 32
      scale_min: [1, 1, 1]
      scale_max: [4, 4, 2]
      sample_q: 2304
      augment: True
      phase: train
      k: 3

  batch_size: 32

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: /nobackup/gpu_d_00993_t3/mtk19837/dataset/sr_data/DIV2K/DIV2K_valid_HR
      first_k: 10
      repeat: 160
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled-cascaded
    args:
      inp_size: 48
      batch_size: 32
      scale_min: [2, 2, 2]
      scale_max: [2, 2, 2]
      sample_q: 2304
      phase: valid

  batch_size: 32

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: clit
  args:
    base_dim: 256    
    head: 8
    r: 3
    imnet_num: 3
    conv_num: 3
    is_cell: True
    local_attn: True

    encoder_spec:
      name: swinir
      args:
        no_upsampling: True
  
    pb_spec:
      name: posenc
      args:
        posenc_type: 'sinusoid'
        posenc_scale: 10
        hidden_dims: 64
        enc_dims: 64
        gamma: 1
  
    imnet_spec:
      name: mlp
      args:
        out_dim: 3
        hidden_list: [256,256,256,256]
        act: 'gelu'

optimizer:
  name: adam
  args:
    lr: 1.e-4
    
epoch_max: 1500
multi_step_lr:
  milestones: [300, 600, 900, 1200]
  gamma: 0.5

epoch_val: 1
epoch_save: 100

resume: ~
pre_train: ~
